imports:
    - { resource: parameters.yml }

parameters:
    app.root_dir: %kernel.root_dir%/..

framework:
    secret: %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    validation: true
    templating:
        engines: ['twig']

twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"